### ISSUE TITLE
Guess what? 

### ISSUE THREAD

**Issue by minanagehsalalma** [Cyber-Atom/Huawei_Thief#7]
they patched it 🤣

any way i need your help with something close to this

if you don't mind :)

**Comment by Zeyad-Azima** [comment]
> they patched it 🤣
> 
> any way i need your help with something close to this
> 
> if you don't mind :)

How can i help you ?

**Comment by minanagehsalalma** [comment]
> > they patched it 🤣
> > any way i need your help with something close to this
> > if you don't mind :)
> 
> How can i help you ?

do you have discord or something we can message on ? 

if so mail it to me 
my email is on my bio 

thanks :)

**Comment by Zeyad-Azima** [comment]
> > > they patched it 🤣
> > > any way i need your help with something close to this
> > > if you don't mind :)
> > 
> > 
> > How can i help you ?
> 
> do you have discord or something we can message on ?
> 
> if so mail it to me my email is on my bio
> 
> thanks :)

Killer_1337#4463
